version: '3.9'

services:
  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: infection_management
    ports:
      - "5433:5432"
    volumes:
      - ./database/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - db_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@db:5432/infection_management


  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - "3030:80"
    depends_on:
      - backend

volumes:
  db_data:
